services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: marka-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    restart: unless-stopped
    networks:
      - tunnel-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: marka-frontend
    ports:
      - "5173:8080"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
    networks:
      - tunnel-network

networks:
  tunnel-network:
    external: true
