name: continuous-integration-main.yml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    if: needs.changes.outputs.frontend == "true"
    needs: changes
    uses: ./.github/workflows/frontend-CI.yml

  backend:
    if: needs.changes.outputs.backend == "true"
    needs: changes
    uses: ./.github/workflows/backend-CI.yml
